version: '3.6'

services:

  mysql-percona:
    build:
      context: mysql-percona
    environment:
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
    - ./data/mysql-percona:/var/lib/mysql
    ports:
    - "3306:3306"
    networks:
    - bridge

  php-fpm:
    build:
      context: ./php-fpm
    volumes:
    - ../:/var/www
    expose:
    - "9000"
    networks:
    - bridge

  nginx:
    image: nginx:alpine
    volumes:
    - ../:/var/www
    - ./nginx/sites/:/etc/nginx/sites-available/
    - ./logs/nginx:/var/log/nginx
    ports:
    - "8000:80"
    restart: always
    environment:
    - NGINX_SERVER_NAME=${NGINX_SERVER_NAME}
    depends_on:
    - php-fpm
    - mysql-percona
    networks:
    - bridge

networks:
  bridge:
    driver: bridge
